dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
name: docflow
description: Um gerenciador de templates e anotações.
version: 1.1.0
environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.3
  sqflite_common_ffi: ^2.3.6
  provider: ^6.1.2
  path_provider: ^2.1.3
  path: ^1.9.0
  flutter_markdown: ^0.7.1
  flutter_highlighter: ^0.1.1
  yaml: ^3.1.2

flutter:
  uses-material-design: true
