name: docflow
description: Um gerenciador de templates e anotações.
version: 0.1.0
environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.3
  sqflite_common_ffi: ^2.3.6
  provider: ^6.1.2

flutter:
  uses-material-design: true
