dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
name: docflow
description: Um gerenciador de templates e anotações.
version: 1.3.0
environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  sqflite: ^2.3.3
  sqflite_common_ffi: ^2.3.6
  provider: ^6.1.2
  path_provider: ^2.1.3
  path: ^1.9.0
  flutter_markdown: ^0.7.1
  flutter_highlighter: ^0.1.1
  yaml: ^3.1.2

flutter:
  generate: true
  # Note: ARB files are in lib/l10n/. We'll generate localization classes
  # explicitly with `flutter gen-l10n` so we can keep Portuguese as the
  # template/default. To add a new language: add `app_xx.arb` in `lib/l10n/`
  # and re-run the gen-l10n command.
  uses-material-design: true
