dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
name: docflow
description: Um gerenciador de templates e anotações.
version: 1.3.1
environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  sqflite: ^2.3.3
  sqflite_common_ffi: ^2.3.6
  provider: ^6.1.2
  path_provider: ^2.1.3
  path: ^1.9.0
  gpt_markdown: ^1.1.4
  flutter_highlighter: ^0.1.1
  yaml: ^3.1.2
  markdown: ^7.3.0

flutter:
  generate: true
  uses-material-design: true
