dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
name: docflow
description: Um gerenciador de templates e anotações.
version: 1.4.0
environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  sqflite: ^2.3.3
  sqflite_common_ffi: ^2.3.6
  provider: ^6.1.2
  path_provider: ^2.1.3
  path: ^1.9.0
  flutter_markdown: ^0.7.1
  flutter_highlighter: ^0.1.1
  markdown: ^7.3.0
  yaml: ^3.1.2
  file_selector: ^1.0.4
  shared_preferences: ^2.1.1
  package_info_plus: ^9.0.0

flutter:
  generate: true
  uses-material-design: true

flutter_intl:
  enabled: true
  arb_dir: lib/l10n
  output_dir: lib/generated
  class_name: AppLocalizations
  main_locale: en
  use_deferred_loading: false
