// Mocks generated by Mockito 5.4.6 from annotations
// in docflow/test/presentation/template_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:docflow/core/utils/result.dart' as _i2;
import 'package:docflow/domain/entities/template.dart' as _i5;
import 'package:docflow/domain/repositories/template_repository.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeResult_0<T> extends _i1.SmartFake implements _i2.Result<T> {
  _FakeResult_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [TemplateRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTemplateRepository extends _i1.Mock
    implements _i3.TemplateRepository {
  MockTemplateRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Result<_i5.Template>> create(_i5.Template? template) =>
      (super.noSuchMethod(
        Invocation.method(
          #create,
          [template],
        ),
        returnValue: _i4.Future<_i2.Result<_i5.Template>>.value(
            _FakeResult_0<_i5.Template>(
          this,
          Invocation.method(
            #create,
            [template],
          ),
        )),
      ) as _i4.Future<_i2.Result<_i5.Template>>);

  @override
  _i4.Future<_i2.Result<_i5.Template>> update(_i5.Template? template) =>
      (super.noSuchMethod(
        Invocation.method(
          #update,
          [template],
        ),
        returnValue: _i4.Future<_i2.Result<_i5.Template>>.value(
            _FakeResult_0<_i5.Template>(
          this,
          Invocation.method(
            #update,
            [template],
          ),
        )),
      ) as _i4.Future<_i2.Result<_i5.Template>>);

  @override
  _i4.Future<_i2.Result<void>> delete(int? id) => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [id],
        ),
        returnValue: _i4.Future<_i2.Result<void>>.value(_FakeResult_0<void>(
          this,
          Invocation.method(
            #delete,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.Result<void>>);

  @override
  _i4.Future<_i2.Result<List<_i5.Template>>> getTemplates({
    int? limit = 10,
    int? offset = 0,
    List<String>? tags = const [],
    String? searchQuery = '',
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTemplates,
          [],
          {
            #limit: limit,
            #offset: offset,
            #tags: tags,
            #searchQuery: searchQuery,
          },
        ),
        returnValue: _i4.Future<_i2.Result<List<_i5.Template>>>.value(
            _FakeResult_0<List<_i5.Template>>(
          this,
          Invocation.method(
            #getTemplates,
            [],
            {
              #limit: limit,
              #offset: offset,
              #tags: tags,
              #searchQuery: searchQuery,
            },
          ),
        )),
      ) as _i4.Future<_i2.Result<List<_i5.Template>>>);

  @override
  _i4.Future<_i2.Result<List<String>>> getAllTags() => (super.noSuchMethod(
        Invocation.method(
          #getAllTags,
          [],
        ),
        returnValue: _i4.Future<_i2.Result<List<String>>>.value(
            _FakeResult_0<List<String>>(
          this,
          Invocation.method(
            #getAllTags,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Result<List<String>>>);

  @override
  _i4.Future<_i2.Result<void>> ensureInitialized() => (super.noSuchMethod(
        Invocation.method(
          #ensureInitialized,
          [],
        ),
        returnValue: _i4.Future<_i2.Result<void>>.value(_FakeResult_0<void>(
          this,
          Invocation.method(
            #ensureInitialized,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Result<void>>);
}
