name: docflow
base: core24
version: '1.3.5'
license: Apache-2.0
title: DocFlow
summary: A document and note template manager with Markdown support.
description: |
  DocFlow simplifies your life by allowing you to easily create, manage, and reuse 
  document and note templates. Ideal for teams and individuals looking to optimize 
  the creation of repetitive documents, DocFlow offers an intuitive interface, 
  fast search, and tag-based organization.

  With an editor that supports Markdown preview and syntax highlighting for code 
  blocks, creating and viewing your templates has never been easier. Switch between 
  light and dark themes for greater visual comfort and use the app in your 
  preferred language, with support for English, Portuguese, and Spanish.

  All your data is stored locally on your device, ensuring your privacy. 
  Increase your productivity and keep your documents standardized with DocFlow.

contact: emerson.comar@estudante.uffs.edu.br
website: https://github.com/EmersonComar/DocFlow
source-code: https://github.com/EmersonComar/DocFlow
issues: https://github.com/EmersonComar/DocFlow/issues
donation: https://github.com/sponsors/EmersonComar

grade: stable
confinement: strict

apps:
  docflow:
    command: docflow
    extensions: [gnome]
    plugs:
      - desktop
      - desktop-legacy
      - wayland
      - x11
      - home

parts:
  docflow:
    source: https://github.com/EmersonComar/DocFlow.git
    source-type: git
    plugin: flutter
    flutter-target: lib/main.dart

    build-packages:
      - libgtk-3-dev
      - pkg-config
      - ninja-build
      - libblkid-dev
      - liblzma-dev
      - libxkbcommon0
    
    stage-packages:
      - zenity
      - libproxy1v5