name: docflow
base: core24
version: '1.3.1'
license: Apache-2.0
summary: Um gerenciador de templates de documentos e notas com suporte a Markdown.
description: |
  O DocFlow simplifica sua vida permitindo que você crie, gerencie e reutilize
  templates de documentos e notas com facilidade. Ideal para equipes e indivíduos
  que buscam otimizar a criação de documentos repetitivos, o DocFlow oferece
  uma interface intuitiva, busca rápida, organização com tags e um editor com
  pré-visualização em Markdown. Aumente sua produtividade e mantenha seus
  documentos padronizados.

grade: stable
confinement: strict

apps:
  docflow:
    command: docflow
    extensions: [gnome]
    plugs:
      - desktop
      - desktop-legacy
      - wayland
      - x11
      - home

parts:
  docflow:
    source: https://github.com/EmersonComar/DocFlow.git
    source-type: git
    plugin: flutter
    flutter-target: lib/main.dart

    build-packages:
      - libgtk-3-dev
      - pkg-config
      - ninja-build
      - libblkid-dev
      - liblzma-dev
      - libxkbcommon0