name: docflow
base: core24
version: '1.1.0'
license: Apache-2.0
summary: Aplicação para gerenciamento de fluxo de documentos
description: |
  DocFlow é uma aplicação que permite gerenciar o fluxo de documentos
  de forma simples e eficiente.

grade: stable
confinement: strict

apps:
  docflow:
    command: docflow
    extensions: [gnome]
    plugs:
      - desktop
      - desktop-legacy
      - wayland
      - x11
      - home

parts:
  docflow:
    source: https://github.com/EmersonComar/DocFlow.git
    source-type: git
    plugin: flutter
    flutter-target: lib/main.dart

    build-packages:
      - libgtk-3-dev
      - pkg-config
      - ninja-build
      - libblkid-dev
      - liblzma-dev
      - libxkbcommon0